[project]
name = "pyme-method-comparison"
version = "1.0.0"
description = "PyME method comparison from Excel accuracy data."
requires-python = ">=3.12"
authors = [
    { name = "Your name", email = "you@example.com" }
]
dependencies = [
    "flet",
    "pandas",
    "openpyxl",
    "python-docx",
    "numpy",
    "plotly",
    "pillow",
    "uncertainties",
    "kaleido"
]

[dependency-groups]
dev = [
    "flet-cli",
    "flet-desktop",
    "flet-web"
]

[tool.flet.metadata]
title = "AI Template"

[tool.flet]
org = "dev.flet"
company = "Flet"
copyright = "Copyright (C) 2023-2026 by Flet"

[tool.flet.app]
path = "src"
